services:
  db:
    image: postgres:15
    container_name: postgres_ticket
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: myredis
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: django_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    env_file:
      - .env

  celery:
    build: .
    container_name: celery_worker
    command: celery -A ticket_system worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    env_file:
      - .env

volumes:
  pgdata:
