# Generated by Django 5.2.7 on 2025-10-14 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='is_red',
            new_name='is_read',
        ),
    ]
