# Generated by Django 5.2.7 on 2025-10-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_rename_is_red_notification_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('اطلاع رسانی', 'Info'), ('هشدار', 'Warning'), ('تبلیغات', 'Promo')], default='اطلاع رسانی', max_length=30),
        ),
    ]
