# Generated by Django 5.2.7 on 2025-10-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_notification_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('N', 'پیام جدید از پشتیبانی'), ('C', 'بسته شدن تیکت'), ('S', 'اعلان سیستمی')], default='N', max_length=30),
        ),
    ]
