# Generated by Django 5.2.7 on 2025-10-14 09:34

import auth_app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.validate_integer, auth_app.models.valid_phone_ir]),
        ),
    ]
