# Generated by Django 5.2.7 on 2025-10-10 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketcategory',
            options={'verbose_name_plural': 'Ticket Categories'},
        ),
    ]
