# Generated by Django 5.2.7 on 2025-10-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0002_alter_ticketcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('L', 'کم-جزئی'), ('M', 'متوسط-پیش\u200cفرض'), ('H', 'بالا-فوری')], default='M', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='admin_status',
            field=models.CharField(choices=[('N', 'جدید'), ('A', 'پاسخ داده شده'), ('S', 'دیده شده'), ('C', 'بسته شده')], default='N', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user_status',
            field=models.CharField(choices=[('P', 'در انتظار پاسخ'), ('A', 'پاسخ داده شده'), ('C', 'بسته شده')], default='P', max_length=10),
        ),
    ]
