# Generated by Django 5.2.7 on 2025-10-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0003_ticket_priority_alter_ticket_admin_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
