# Generated by Django 5.2.7 on 2025-10-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_app', '0005_alter_ticketcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('1', 'کم-جزئی'), ('2', 'متوسط-پیش\u200cفرض'), ('3', 'بالا-فوری')], default='2', max_length=10),
        ),
    ]
